on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket with '${{ matrix.os }}'"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: Bogdanp/setup-racket@v1.9.1
        with:
          architecture: x64
          distribution: full
          variant: 'CS'
          version: '8.11'
      - name: Installing fractal-clock and its dependencies
        run: raco pkg install --no-docs --auto --name fractal-clock
      - name: Compiling fractal-clock and release the binary
        run:   |
          if [ "$RUNNER_OS" == "Linux" ]; then
              raco exe -o main --gui main.rkt && raco distribute fractal-clock main
          elif [ "$RUNNER_OS" == "macOS" ]; then
              raco exe -o main --gui main.rkt && raco distribute fractal-clock main.app
          elif [ "$RUNNER_OS" == "Windows" ]; then
              raco exe -o main --gui main.rkt && raco distribute fractal-clock main.exe
          else
              echo "$RUNNER_OS not supported"
              exit 1
          fi
        shell: bash
      - name: Uploading build artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: fractal-clock-${{ matrix.os }}
          path: fractal-clock*
  